spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: ${username}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: update

security-config:
  unauthorized: /error, /webclient,  /register, /books/byAuthors, /books/getNewBooks /genres, /authors, /review, /publishing, /editionTyp, /authenticate, /test/anyone
  user: /test/user*/**, /books/rent, /books/addReview/, /books/rent

