spring:
  datasource:
    url: jdbc:postgresql://dbpostgres:5432/library
    username: ${dbusername}
    password: ${dbpassword}

  jpa:
    hibernate:
      ddl-auto: update

security-config:
  unauthorized: /register, /books*/**, /genres, /authors, /review, /publishing, /editionType, /authenticate
  user: /books/rent, /review/add