spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: ${username}
    password: ${password}

  jpa:
    hibernate:
      ddl-auto: update

security-config:
  unauthorized: /register, /books*/**, /genres, /authors, /review, /publishing, /editionType, /authenticate
  user: /books/rent, /review/add, /user, /user/byName